---
- name: Push a script and run it
  hosts: localhost

  tasks:
    - script: /home/student/mycode/run_a_script/pyhello.py
      args:
        executable: python3
      register: results

    - debug:
        msg: "Here is what came back: {{ results }}"

    - debug:
        msg: "The output of the Python is {{ results.stdout }}"
